### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by xabree** [Chalarangelo/react-mini.css#2]
need help, error when using mini.css-react

npm i --save-dev mini.css mini.css-react

use in component 
import {GridRow, GridColumn, Header, Drawer, DrawerToggle, Checkbox, GridContainer} from 'mini.css-react'

then error 
```
/var/www/test/node_modules/mini.css-react/dist/mini.css-react.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by Chalarangelo** [comment]
Hi, thanks for reporting this! I will be looking into it shortly!
