### ISSUE TITLE
'mini.css-react' does not contain an export named 'GridContainer'

### ISSUE THREAD

**Issue by bodrovphone** [Chalarangelo/react-mini.css#3]
Greetings! 

I've encountered an issue while importing GridContainer component. Can you advise please?

`import {GridContainer} from 'mini.css-react';`

**Comment by Chalarangelo** [comment]
Hi, thanks for reporting this! I will be looking into it shortly!

**Comment by Chalarangelo** [comment]
Resolved in #4
